#### Java12/15上课笔记

##### 异常处理

在发生错误之后，把错误局限在一个模块中，异常处理不能解决问题。

```java
try{
    //可能产生异常的代码
 }catch (异常类型 e) {
    //异常处理代码
           }
  catch (异常类型 e) {
    //异常处理代码
           }
  catch (异常类型 e) {
    //异常处理代码
           }finally{//放必要的代码，一般是善后的代码
  }//finally可以没有
```

一个try可以拥有多个catch。

finally：不管你发不发生异常，不管异常有没有捕获，finally中的语句一定会发生。如果finall中有异常发生，则其后面的程序不会运行，前面的程序会运行。

```java
int a=10;
        int b=0;
        int c=a+b;
        File file=new File("C:\\Users\\lenovo\\Desktop\\Test1215.txt");
        try{
            int d=a/b;
            file.createNewFile();
        }catch (IOException e){
            System.out.println("ll");
            e.printStackTrace();  //打印栈中的信息
        }finally {
            System.out.println("hahahahaha");
        }
```

结果

```java
hahahahaha
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at Test1215.Test1215.main(Test1215.java:53)

Process finished with exit code 1
```

try中可以发生很多异常，但是运行时真正发生的异常只会发生一个，发生try语句中从上到下出现的第一个异常。如果try中发生的异常在众多的catch语句中都能被捕捉到，那么当异常真正发生时，会从上到下找到第一个能捕捉到异常的catch语句。所以，越精确的catch语句要放到越前面。把子类放前面，把父类放后面。

当你只能确定会有异常发生，但是无法确定具体会发生什么异常时，可以使用Exception,所有的异常都是Exception的子类。

数组越界访问，NullPointerException，ArithmeticException不是一定要异常处理的异常。

```java
String s=null;//NullPointerException
        try{
            int l=s.length();
            System.out.println(l);
        }catch (Exception e) {
            System.out.println("llll");
        }
```

```java
int a=10;//ArithmeticException
        int b=0;
        int c=a+b;
        try {
            int d=a/b;
        }catch (ArithmeticException e){
            System.out.println("kkk");;
        }
```

##### 如何构建一个完备的异常类

1、定义异常类，基于Java工程师准备的Exception。

2、标注需要进行异常处理的方法。

​			（1）该方法体中至少有一条语句会抛出异常对象

​			（2）该方法签名处需要声明异常类型。

```java
public class MyException extends Exception{
    private String msg="hello";
    public String getMsg(){
        return msg;
    }
    public void setMsg(String msg){
        this.msg=msg;
    }
    public MyException(String msg){
        super();
        this.msg=msg;
    }
    public MyException(){
        super();
    }
}
```

```java
public class ExceptionTest extends Exception {
    public void toSomething(String name) throws MyException, IOException {
        if(name.equals("admin")) throw new MyException("sfdjh");
        else if(name.equals("tin")) throw new IOException();
    }
}
```

```java
public class TestException {
    public static void main(String[] args) {
        ExceptionTest et=new ExceptionTest();
        try {
            et.toSomething("admin");
        }catch (MyException e){
            e.printStackTrace();
        }
    }
}
```

多个异常类

```java
public class ExceptionTest extends Exception {
    public void toSomething(String name) throws MyException, IOException {
        if(name.equals("admin")) throw new MyException("sfdjh");
        else if(name.equals("tin")) throw new IOException();
    }
}
```

